---
AWSTemplateFormatVersion: 2010-09-09

Parameters:
    NotificationAddress:
        Type: String

    SnsTopicName:
        Type: String

Resources:
    SnsTopic:
        Type: "AWS::SNS::Topic"
        Properties:
            DisplayName: !Ref SnsTopicName
            TopicName: !Ref SnsTopicName

    SnsSubscription:
        Type: "AWS::SNS::Subscription"
        Properties:
            Endpoint: !Ref NotificationAddress
            Protocol: email
            TopicArn: !Ref SnsTopic

Outputs:
    TopicArn:
        Value: !Ref SnsTopic
